import React from 'react';

export const ProductData = {
  washingMachines: [
    { name: "Washing Machine A", description: "Efficient and durable washing machine.", price: "₹15,000", image: "https://via.placeholder.com/150?text=Washing+Machine+A" },
    { name: "Washing Machine B", description: "High capacity, fast washing cycle.", price: "₹20,000", image: "https://via.placeholder.com/150?text=Washing+Machine+B" },
    { name: "Washing Machine C", description: "Energy-efficient with quick spin cycle.", price: "₹18,000", image: "https://via.placeholder.com/150?text=Washing+Machine+C" },
    { name: "Washing Machine D", description: "Compact design with smart features.", price: "₹12,500", image: "https://via.placeholder.com/150?text=Washing+Machine+D" },
    { name: "Washing Machine E", description: "Top load washing machine with advanced features.", price: "₹22,000", image: "https://via.placeholder.com/150?text=Washing+Machine+E" },
    { name: "Washing Machine F", description: "Front load with steam technology for better wash.", price: "₹25,000", image: "https://via.placeholder.com/150?text=Washing+Machine+F" },
    { name: "Washing Machine G", description: "Silent operation and energy-saving features.", price: "₹19,000", image: "https://via.placeholder.com/150?text=Washing+Machine+G" },
    { name: "Washing Machine H", description: "Quick wash cycle for busy schedules.", price: "₹17,000", image: "https://via.placeholder.com/150?text=Washing+Machine+H" },
    { name: "Washing Machine I", description: "Heavy-duty washing machine for large families.", price: "₹30,000", image: "https://via.placeholder.com/150?text=Washing+Machine+I" },
    { name: "Washing Machine J", description: "Smart washing machine with Wi-Fi connectivity.", price: "₹24,000", image: "https://via.placeholder.com/150?text=Washing+Machine+J" },
    { name: "Washing Machine K", description: "Automatic washing machine with multiple modes.", price: "₹16,500", image: "https://via.placeholder.com/150?text=Washing+Machine+K" },
    { name: "Washing Machine L", description: "Space-saving design with 6kg capacity.", price: "₹13,000", image: "https://via.placeholder.com/150?text=Washing+Machine+L" },
    { name: "Washing Machine M", description: "Fully automatic with quick dry function.", price: "₹21,000", image: "https://via.placeholder.com/150?text=Washing+Machine+M" },
    { name: "Washing Machine N", description: "High-performance motor with low noise.", price: "₹23,000", image: "https://via.placeholder.com/150?text=Washing+Machine+N" },
    { name: "Washing Machine O", description: "Eco-friendly and water-efficient design.", price: "₹14,500", image: "https://via.placeholder.com/150?text=Washing+Machine+O" },
    { name: "Washing Machine P", description: "Premium washing machine with smart sensors.", price: "₹27,000", image: "https://via.placeholder.com/150?text=Washing+Machine+P" },
    { name: "Washing Machine Q", description: "Perfect for small apartments with 5kg capacity.", price: "₹12,000", image: "https://via.placeholder.com/150?text=Washing+Machine+Q" },
    { name: "Washing Machine R", description: "High-efficiency motor for faster washing.", price: "₹19,500", image: "https://via.placeholder.com/150?text=Washing+Machine+R" },
    { name: "Washing Machine S", description: "Smart controls and voice assistant integration.", price: "₹26,000", image: "https://via.placeholder.com/150?text=Washing+Machine+S" },
    { name: "Washing Machine T", description: "Compact design with a heavy-duty performance.", price: "₹20,500", image: "https://via.placeholder.com/150?text=Washing+Machine+T" }
  ],
  microwaveOvens: [
    { name: "Microwave Oven A", description: "Quick and efficient heating for your food.", price: "₹7,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+A" },
    { name: "Microwave Oven B", description: "Microwave with convection feature for baking.", price: "₹10,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+B" },
    { name: "Microwave Oven C", description: "Compact design with easy-to-use settings.", price: "₹8,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+C" },
    { name: "Microwave Oven D", description: "High power microwave for quick cooking.", price: "₹9,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+D" },
    { name: "Microwave Oven E", description: "Smart microwave with preset cooking modes.", price: "₹12,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+E" },
    { name: "Microwave Oven F", description: "Large capacity with grill function.", price: "₹11,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+F" },
    { name: "Microwave Oven G", description: "Eco-friendly design with low energy consumption.", price: "₹9,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+G" },
    { name: "Microwave Oven H", description: "Easy-to-clean with touch panel controls.", price: "₹8,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+H" },
    { name: "Microwave Oven I", description: "Touchscreen microwave with multi-cooking options.", price: "₹13,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+I" },
    { name: "Microwave Oven J", description: "Combination microwave with superior heating.", price: "₹14,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+J" },
    { name: "Microwave Oven K", description: "Convection microwave for advanced cooking.", price: "₹15,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+K" },
    { name: "Microwave Oven L", description: "Sleek design with quick start feature.", price: "₹7,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+L" },
    { name: "Microwave Oven M", description: "Family-sized microwave with multiple settings.", price: "₹10,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+M" },
    { name: "Microwave Oven N", description: "Affordable microwave with large turntable.", price: "₹6,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+N" },
    { name: "Microwave Oven O", description: "Digital display microwave with timer options.", price: "₹9,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+O" },
    { name: "Microwave Oven P", description: "Multi-functional microwave for everyday use.", price: "₹11,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+P" },
    { name: "Microwave Oven Q", description: "Compact microwave ideal for small spaces.", price: "₹7,800", image: "https://via.placeholder.com/150?text=Microwave+Oven+Q" },
    { name: "Microwave Oven R", description: "Fast cooking with smart heating technology.", price: "₹13,500", image: "https://via.placeholder.com/150?text=Microwave+Oven+R" },
    { name: "Microwave Oven S", description: "Affordable and reliable for everyday meals.", price: "₹6,000", image: "https://via.placeholder.com/150?text=Microwave+Oven+S" },
    { name: "Microwave Oven T", description: "Efficient microwave with multiple preset modes.", price: "₹8,200", image: "https://via.placeholder.com/150?text=Microwave+Oven+T" }
  ],
  televisions: [
    { name: "TV Model A", description: "4K resolution with HDR for stunning visuals.", price: "₹40,000", image: "https://via.placeholder.com/150?text=TV+Model+A" },
    { name: "TV Model B", description: "Smart TV with built-in apps and voice control.", price: "₹50,000", image: "https://via.placeholder.com/150?text=TV+Model+B" },
    { name: "TV Model C", description: "OLED technology for vibrant colors and deep blacks.", price: "₹70,000", image: "https://via.placeholder.com/150?text=TV+Model+C" },
    { name: "TV Model D", description: "Curved screen for a more immersive experience.", price: "₹35,000", image: "https://via.placeholder.com/150?text=TV+Model+D" },
    { name: "TV Model E", description: "Full HD resolution with ultra-thin design.", price: "₹30,000", image: "https://via.placeholder.com/150?text=TV+Model+E" },
    { name: "TV Model F", description: "LED TV with energy-efficient features.", price: "₹25,000", image: "https://via.placeholder.com/150?text=TV+Model+F" },
    { name: "TV Model G", description: "Smart TV with 4K resolution and voice commands.", price: "₹60,000", image: "https://via.placeholder.com/150?text=TV+Model+G" },
    { name: "TV Model H", description: "High-definition display with built-in streaming apps.", price: "₹45,000", image: "https://via.placeholder.com/150?text=TV+Model+H" },
    { name: "TV Model I", description: "Large screen for immersive viewing experience.", price: "₹55,000", image: "https://via.placeholder.com/150?text=TV+Model+I" },
    { name: "TV Model J", description: "HDR and Dolby Vision support for enhanced visuals.", price: "₹65,000", image: "https://via.placeholder.com/150?text=TV+Model+J" },
    { name: "TV Model K", description: "QLED technology with superior brightness.", price: "₹75,000", image: "https://via.placeholder.com/150?text=TV+Model+K" },
    { name: "TV Model L", description: "Compact smart TV ideal for small spaces.", price: "₹20,000", image: "https://via.placeholder.com/150?text=TV+Model+L" },
    { name: "TV Model M", description: "High refresh rate for smooth motion and gaming.", price: "₹40,000", image: "https://via.placeholder.com/150?text=TV+Model+M" },
    { name: "TV Model N", description: "Premium 8K TV for the ultimate viewing experience.", price: "₹100,000", image: "https://via.placeholder.com/150?text=TV+Model+N" },
    { name: "TV Model O", description: "LED TV with a sleek design and smart features.", price: "₹28,000", image: "https://via.placeholder.com/150?text=TV+Model+O" },
    { name: "TV Model P", description: "Affordable TV with decent quality and design.", price: "₹22,000", image: "https://via.placeholder.com/150?text=TV+Model+P" },
    { name: "TV Model Q", description: "Large screen with sharp 4K resolution.", price: "₹50,000", image: "https://via.placeholder.com/150?text=TV+Model+Q" },
    { name: "TV Model R", description: "OLED TV with ultra-clear display.", price: "₹85,000", image: "https://via.placeholder.com/150?text=TV+Model+R" },
    { name: "TV Model S", description: "Smart TV with Alexa and Google Assistant support.", price: "₹65,000", image: "https://via.placeholder.com/150?text=TV+Model+S" },
    { name: "TV Model T", description: "Slim and sleek design with superior picture quality.", price: "₹60,000", image: "https://via.placeholder.com/150?text=TV+Model+T" }
  ],
  airConditioners: [
    { name: "AC Model A", description: "Energy-efficient split AC for cooling and heating.", price: "₹35,000", image: "https://via.placeholder.com/150?text=AC+Model+A" },
    { name: "AC Model B", description: "Smart AC with Wi-Fi control and eco-friendly design.", price: "₹45,000", image: "https://via.placeholder.com/150?text=AC+Model+B" },
    { name: "AC Model C", description: "High-performance AC with rapid cooling.", price: "₹40,000", image: "https://via.placeholder.com/150?text=AC+Model+C" },
    { name: "AC Model D", description: "Portable AC with easy installation and powerful cooling.", price: "₹25,000", image: "https://via.placeholder.com/150?text=AC+Model+D" },
    { name: "AC Model E", description: "Energy-efficient inverter AC for larger rooms.", price: "₹50,000", image: "https://via.placeholder.com/150?text=AC+Model+E" },
    { name: "AC Model F", description: "Compact design AC for small rooms.", price: "₹20,000", image: "https://via.placeholder.com/150?text=AC+Model+F" },
    { name: "AC Model G", description: "Smart features with temperature control and dehumidifier.", price: "₹38,000", image: "https://via.placeholder.com/150?text=AC+Model+G" },
    { name: "AC Model H", description: "Split AC with anti-bacterial filter.", price: "₹42,000", image: "https://via.placeholder.com/150?text=AC+Model+H" },
    { name: "AC Model I", description: "Best-in-class cooling with quiet operation.", price: "₹48,000", image: "https://via.placeholder.com/150?text=AC+Model+I" },
    { name: "AC Model J", description: "Inverter AC with low power consumption.", price: "₹40,500", image: "https://via.placeholder.com/150?text=AC+Model+J" },
    { name: "AC Model K", description: "Energy-saving AC with quick cooling.", price: "₹37,000", image: "https://via.placeholder.com/150?text=AC+Model+K" },
    { name: "AC Model L", description: "Stylish AC with easy maintenance.", price: "₹30,000", image: "https://via.placeholder.com/150?text=AC+Model+L" },
    { name: "AC Model M", description: "Cooling system for medium-sized rooms.", price: "₹32,000", image: "https://via.placeholder.com/150?text=AC+Model+M" },
    { name: "AC Model N", description: "Dual function AC with both cooling and heating.", price: "₹50,000", image: "https://via.placeholder.com/150?text=AC+Model+N" },
    { name: "AC Model O", description: "Multi-functional AC with air purifier feature.", price: "₹55,000", image: "https://via.placeholder.com/150?text=AC+Model+O" },
    { name: "AC Model P", description: "Portable AC with remote control.", price: "₹25,000", image: "https://via.placeholder.com/150?text=AC+Model+P" },
    { name: "AC Model Q", description: "High-end split AC with silent operation.", price: "₹60,000", image: "https://via.placeholder.com/150?text=AC+Model+Q" },
    { name: "AC Model R", description: "Advanced cooling with smart controls.", price: "₹52,000", image: "https://via.placeholder.com/150?text=AC+Model+R" },
    { name: "AC Model S", description: "Inverter split AC with fast cooling technology.", price: "₹55,500", image: "https://via.placeholder.com/150?text=AC+Model+S" },
    { name: "AC Model T", description: "Smart AC with temperature regulation and eco-friendly design.", price: "₹60,000", image: "https://via.placeholder.com/150?text=AC+Model+T" }
  ]
};

